# Set update schedule for GitHub Actions
# See https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
