include: package:pedantic/analysis_options.yaml
analyzer:
  errors:
    todo: ignore
    # Lint provided by pkg:pedantic – should fix this!
    unawaited_futures: ignore
linter:
  rules:
    - prefer_generic_function_type_aliases
    - prefer_typing_uninitialized_variables
    - unnecessary_const
    - unnecessary_new
