include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    todo: ignore
    # Lint provided by pkg:pedantic – should fix this!
    unawaited_futures: ignore

linter:
  rules:
    - prefer_typing_uninitialized_variables
