# https://dart.dev/guides/language/analysis-options
include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
  errors:
    only_throw_errors: ignore
    unawaited_futures: ignore

linter:
  rules:
    - avoid_unused_constructor_parameters
    - comment_references
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - no_runtimeType_toString
    - package_api_docs
    - prefer_relative_imports
    - test_types_in_equals
    - use_super_parameters
